### ISSUE TITLE
Could not cast value of type

### ISSUE THREAD

**Issue by jefferyleo** [one-signal/OneSignal-iOS-SDK#6]
When I press the push notifications call back, I got the news, but after that it crash automatically due to this error. How to solve this casting issue?

OneSignal Notification opened:
Message: test
2016-01-06 10:02:01.082 ChinaPress[2957:1103987] additionalData: {
    newsid = 447362;
    sound = default;
}
Could not cast value of type '__NSCFNumber' (0x377f1c28) to 'NSString' (0x377f773c).

**Comment by moridaffy** [comment]
This issue is still present on 5.2.4 SDK version. Experiencing crash on a button tap inside one of in-app message screens, both on real device and simulator running iOS 18.0.

Receiving SIGABRT in AppDelegate with a following message:
`Could not cast value of type '__NSCFNumber' (0x377f1c28) to 'NSString' (0x377f773c)`
